import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import NavigationWrapper from "@/components/navigation-wrapper";
import GridBackgroundWrapper from "@/components/grid-background-wrapper";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DAgents",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* Grid Background */}
          <GridBackgroundWrapper />

          <div className="flex min-h-screen flex-col">
            {/* We'll import the Navigation dynamically to avoid server/client mismatch issues */}
            <header className="pt-6">
              <NavigationWrapper />
            </header>
            <main className="flex-1">
              <Toaster />
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
